[package]
name = "rust-mqtt-client"
version = "0.1.0"
authors = ["Henk van Asselt <Henk.van.Asselt@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rumqttc = "0.6.0"
thiserror = "1.0.21"
slog = "2.7.0"